//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.wlp.wlpecm.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfArrayOf_tns3_nillable_IndexValuePair complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfArrayOf_tns3_nillable_IndexValuePair">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ArrayOf_tns3_nillable_IndexValuePair" type="{http://service.wlpecm.wlp.com}ArrayOf_tns3_nillable_IndexValuePair" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfArrayOf_tns3_nillable_IndexValuePair", propOrder = {
    "arrayOfTns3NillableIndexValuePair"
})
public class ArrayOfArrayOfTns3NillableIndexValuePair {

    @XmlElement(name = "ArrayOf_tns3_nillable_IndexValuePair", nillable = true)
    protected List<ArrayOfTns3NillableIndexValuePair> arrayOfTns3NillableIndexValuePair;

    /**
     * Gets the value of the arrayOfTns3NillableIndexValuePair property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arrayOfTns3NillableIndexValuePair property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArrayOfTns3NillableIndexValuePair().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArrayOfTns3NillableIndexValuePair }
     * 
     * 
     */
    public List<ArrayOfTns3NillableIndexValuePair> getArrayOfTns3NillableIndexValuePair() {
        if (arrayOfTns3NillableIndexValuePair == null) {
            arrayOfTns3NillableIndexValuePair = new ArrayList<ArrayOfTns3NillableIndexValuePair>();
        }
        return this.arrayOfTns3NillableIndexValuePair;
    }

}
