//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.wlp.wlpecm.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.wlp.wlpecm.service.requestdto.GetContentReqDTO;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objRequestGetContentReqDTO" type="{http://requestdto.service.wlpecm.wlp.com}GetContentReqDTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objRequestGetContentReqDTO"
})
@XmlRootElement(name = "getContent")
public class GetContent {

    @XmlElement(required = true, nillable = true)
    protected GetContentReqDTO objRequestGetContentReqDTO;

    /**
     * Gets the value of the objRequestGetContentReqDTO property.
     * 
     * @return
     *     possible object is
     *     {@link GetContentReqDTO }
     *     
     */
    public GetContentReqDTO getObjRequestGetContentReqDTO() {
        return objRequestGetContentReqDTO;
    }

    /**
     * Sets the value of the objRequestGetContentReqDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetContentReqDTO }
     *     
     */
    public void setObjRequestGetContentReqDTO(GetContentReqDTO value) {
        this.objRequestGetContentReqDTO = value;
    }

}
