//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.wlp.wlpecm.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.wlp.wlpecm.service.requestdto.GetRepositoryStatusReqDTO;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objRequestGetRepositoryStatusReqDTO" type="{http://requestdto.service.wlpecm.wlp.com}GetRepositoryStatusReqDTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objRequestGetRepositoryStatusReqDTO"
})
@XmlRootElement(name = "getRepositoryStatus")
public class GetRepositoryStatus {

    @XmlElement(required = true, nillable = true)
    protected GetRepositoryStatusReqDTO objRequestGetRepositoryStatusReqDTO;

    /**
     * Gets the value of the objRequestGetRepositoryStatusReqDTO property.
     * 
     * @return
     *     possible object is
     *     {@link GetRepositoryStatusReqDTO }
     *     
     */
    public GetRepositoryStatusReqDTO getObjRequestGetRepositoryStatusReqDTO() {
        return objRequestGetRepositoryStatusReqDTO;
    }

    /**
     * Sets the value of the objRequestGetRepositoryStatusReqDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetRepositoryStatusReqDTO }
     *     
     */
    public void setObjRequestGetRepositoryStatusReqDTO(GetRepositoryStatusReqDTO value) {
        this.objRequestGetRepositoryStatusReqDTO = value;
    }

}
