//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.wlp.wlpecm.service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wlp.wlpecm.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wlp.wlpecm.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetContentResponse }
     * 
     */
    public GetContentResponse createGetContentResponse() {
        return new GetContentResponse();
    }

    /**
     * Create an instance of {@link GetListing }
     * 
     */
    public GetListing createGetListing() {
        return new GetListing();
    }

    /**
     * Create an instance of {@link GetRepositoryList }
     * 
     */
    public GetRepositoryList createGetRepositoryList() {
        return new GetRepositoryList();
    }

    /**
     * Create an instance of {@link GetRepositoryListResponse }
     * 
     */
    public GetRepositoryListResponse createGetRepositoryListResponse() {
        return new GetRepositoryListResponse();
    }

    /**
     * Create an instance of {@link GetContent }
     * 
     */
    public GetContent createGetContent() {
        return new GetContent();
    }

    /**
     * Create an instance of {@link UpdateContentMetadata }
     * 
     */
    public UpdateContentMetadata createUpdateContentMetadata() {
        return new UpdateContentMetadata();
    }

    /**
     * Create an instance of {@link GetRepositoryStatus }
     * 
     */
    public GetRepositoryStatus createGetRepositoryStatus() {
        return new GetRepositoryStatus();
    }

    /**
     * Create an instance of {@link GetListingResponse }
     * 
     */
    public GetListingResponse createGetListingResponse() {
        return new GetListingResponse();
    }

    /**
     * Create an instance of {@link StoreContent }
     * 
     */
    public StoreContent createStoreContent() {
        return new StoreContent();
    }

    /**
     * Create an instance of {@link UpdateContentMetadataResponse }
     * 
     */
    public UpdateContentMetadataResponse createUpdateContentMetadataResponse() {
        return new UpdateContentMetadataResponse();
    }

    /**
     * Create an instance of {@link GetObjectClassResponse }
     * 
     */
    public GetObjectClassResponse createGetObjectClassResponse() {
        return new GetObjectClassResponse();
    }

    /**
     * Create an instance of {@link GetObjectClass }
     * 
     */
    public GetObjectClass createGetObjectClass() {
        return new GetObjectClass();
    }

    /**
     * Create an instance of {@link GetRepositoryStatusResponse }
     * 
     */
    public GetRepositoryStatusResponse createGetRepositoryStatusResponse() {
        return new GetRepositoryStatusResponse();
    }

    /**
     * Create an instance of {@link StoreContentResponse }
     * 
     */
    public StoreContentResponse createStoreContentResponse() {
        return new StoreContentResponse();
    }

    /**
     * Create an instance of {@link ArrayOfXsdNillableString }
     * 
     */
    public ArrayOfXsdNillableString createArrayOfXsdNillableString() {
        return new ArrayOfXsdNillableString();
    }

    /**
     * Create an instance of {@link ArrayOfTns3NillableObjectClassInfo }
     * 
     */
    public ArrayOfTns3NillableObjectClassInfo createArrayOfTns3NillableObjectClassInfo() {
        return new ArrayOfTns3NillableObjectClassInfo();
    }

    /**
     * Create an instance of {@link ArrayOfArrayOfTns3NillableIndexValuePair }
     * 
     */
    public ArrayOfArrayOfTns3NillableIndexValuePair createArrayOfArrayOfTns3NillableIndexValuePair() {
        return new ArrayOfArrayOfTns3NillableIndexValuePair();
    }

    /**
     * Create an instance of {@link ArrayOfTns3NillableIndexValuePair }
     * 
     */
    public ArrayOfTns3NillableIndexValuePair createArrayOfTns3NillableIndexValuePair() {
        return new ArrayOfTns3NillableIndexValuePair();
    }

}
