//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.wlp.wlpecm.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;
import com.wellpoint.esb.header.v3.ESBHeaderType;

@WebService(name = "WLPECM", targetNamespace = "http://service.wlpecm.wlp.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WLPECM {


    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns com.wlp.wlpecm.service.GetRepositoryListResponse
     * @throws Fault
     */
    @WebMethod(action = "getRepositoryList")
    @WebResult(name = "getRepositoryListResponse", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
    public GetRepositoryListResponse getRepositoryList(
        @WebParam(name = "ESBHeader", targetNamespace = "http://wellpoint.com/esb/header/v3", mode = WebParam.Mode.INOUT, partName = "header")
        Holder<ESBHeaderType> header,
        @WebParam(name = "getRepositoryList", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
        GetRepositoryList parameters)
        throws Fault
    ;

    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns com.wlp.wlpecm.service.UpdateContentMetadataResponse
     * @throws Fault
     */
    @WebMethod(action = "updateContentMetadata")
    @WebResult(name = "updateContentMetadataResponse", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
    public UpdateContentMetadataResponse updateContentMetadata(
        @WebParam(name = "ESBHeader", targetNamespace = "http://wellpoint.com/esb/header/v3", mode = WebParam.Mode.INOUT, partName = "header")
        Holder<ESBHeaderType> header,
        @WebParam(name = "updateContentMetadata", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
        UpdateContentMetadata parameters)
        throws Fault
    ;

    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns com.wlp.wlpecm.service.GetRepositoryStatusResponse
     * @throws Fault
     */
    @WebMethod(action = "getRepositoryStatus")
    @WebResult(name = "getRepositoryStatusResponse", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
    public GetRepositoryStatusResponse getRepositoryStatus(
        @WebParam(name = "ESBHeader", targetNamespace = "http://wellpoint.com/esb/header/v3", mode = WebParam.Mode.INOUT, partName = "header")
        Holder<ESBHeaderType> header,
        @WebParam(name = "getRepositoryStatus", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
        GetRepositoryStatus parameters)
        throws Fault
    ;

    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns com.wlp.wlpecm.service.GetObjectClassResponse
     * @throws Fault
     */
    @WebMethod(action = "getObjectClass")
    @WebResult(name = "getObjectClassResponse", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
    public GetObjectClassResponse getObjectClass(
        @WebParam(name = "ESBHeader", targetNamespace = "http://wellpoint.com/esb/header/v3", mode = WebParam.Mode.INOUT, partName = "header")
        Holder<ESBHeaderType> header,
        @WebParam(name = "getObjectClass", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
        GetObjectClass parameters)
        throws Fault
    ;

    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns com.wlp.wlpecm.service.GetListingResponse
     * @throws Fault
     */
    @WebMethod(action = "getListing")
    @WebResult(name = "getListingResponse", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
    public GetListingResponse getListing(
        @WebParam(name = "ESBHeader", targetNamespace = "http://wellpoint.com/esb/header/v3", mode = WebParam.Mode.INOUT, partName = "header")
        Holder<ESBHeaderType> header,
        @WebParam(name = "getListing", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
        GetListing parameters)
        throws Fault
    ;

    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns com.wlp.wlpecm.service.GetContentResponse
     * @throws Fault
     */
    @WebMethod(action = "getContent")
    @WebResult(name = "getContentResponse", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
    public GetContentResponse getContent(
        @WebParam(name = "ESBHeader", targetNamespace = "http://wellpoint.com/esb/header/v3", mode = WebParam.Mode.INOUT, partName = "header")
        Holder<ESBHeaderType> header,
        @WebParam(name = "getContent", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
        GetContent parameters)
        throws Fault
    ;

    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns com.wlp.wlpecm.service.StoreContentResponse
     * @throws Fault
     */
    @WebMethod(action = "storeContent")
    @WebResult(name = "storeContentResponse", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
    public StoreContentResponse storeContent(
        @WebParam(header=true, name = "ESBHeader", targetNamespace = "http://wellpoint.com/esb/header/v3", mode = WebParam.Mode.INOUT, partName = "header")
        Holder<ESBHeaderType> header,
        @WebParam(name = "storeContent", targetNamespace = "http://service.wlpecm.wlp.com", partName = "parameters")
        StoreContent parameters)
        throws Fault
    ;

}
