//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//

package com.wlp.wlpecm.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.handler.HandlerResolver;

import com.wellpoint.esb.header.v3.MyHandlerResolver;

@WebServiceClient(name = "WLPECMFileNet", targetNamespace = "http://service.wlpecm.wlp.com", wsdlLocation = "classpath:WLPECMFileNetVer2_0.wsdl")
public class WLPECMFileNet extends Service {

	private static URL WLPECMFILENET_WSDL_LOCATION;
	private final static WebServiceException WLPECMFILENET_EXCEPTION;
	private final static QName WLPECMFILENET_QNAME = new QName("http://service.wlpecm.wlp.com", "WLPECMFileNet");

	static {
		WLPECMFILENET_WSDL_LOCATION = WLPECMFileNet.class.getClassLoader().getResource("WLPECMFileNetVer2_0.wsdl");
		// WLPECMFILENET_WSDL_LOCATION = new
		// URL("file:/wsapps/eca/deployment/config/WLPECMFileNetVer2_0.wsdl");
		WebServiceException e = null;
		if (WLPECMFILENET_WSDL_LOCATION == null) {
			e = new WebServiceException(
					"Cannot find 'WLPECMFileNetVer2_0.wsdl' wsdl. Place the resource correctly in the classpath.");
		}
		WLPECMFILENET_EXCEPTION = e;
	}

	public WLPECMFileNet() {
		super(__getWsdlLocation(), WLPECMFILENET_QNAME);
	}

	public WLPECMFileNet(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	/**
	 * 
	 * @return returns WLPECM
	 */
	@WebEndpoint(name = "WLPECM")
	public WLPECM getWLPECM() {
		MyHandlerResolver hs = new MyHandlerResolver();
		super.setHandlerResolver(hs);
		return super.getPort(new QName("http://service.wlpecm.wlp.com", "WLPECM"), WLPECM.class);
	}

	private static URL __getWsdlLocation() {
		if (WLPECMFILENET_EXCEPTION != null) {
			throw WLPECMFILENET_EXCEPTION;
		}
		return WLPECMFILENET_WSDL_LOCATION;
	}

}
