//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.wlp.wlpecm.service.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.wlp.wlpecm.service.ArrayOfXsdNillableString;


/**
 * <p>Java class for ObjectClassInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectClassInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="className" type="{http://service.wlpecm.wlp.com}ArrayOf_xsd_nillable_string"/>
 *         &lt;element name="objectStore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectClassInfo", propOrder = {
    "className",
    "objectStore"
})
public class ObjectClassInfo {

    @XmlElement(required = true, nillable = true)
    protected ArrayOfXsdNillableString className;
    @XmlElement(required = true, nillable = true)
    protected String objectStore;

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfXsdNillableString }
     *     
     */
    public ArrayOfXsdNillableString getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfXsdNillableString }
     *     
     */
    public void setClassName(ArrayOfXsdNillableString value) {
        this.className = value;
    }

    /**
     * Gets the value of the objectStore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectStore() {
        return objectStore;
    }

    /**
     * Sets the value of the objectStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectStore(String value) {
        this.objectStore = value;
    }

}
