//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.wlp.wlpecm.service.common;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wlp.wlpecm.service.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WLPECMException_QNAME = new QName("http://common.service.wlpecm.wlp.com", "WLPECMException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wlp.wlpecm.service.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WLPECMException }
     * 
     */
    public WLPECMException createWLPECMException() {
        return new WLPECMException();
    }

    /**
     * Create an instance of {@link IndexValuePair }
     * 
     */
    public IndexValuePair createIndexValuePair() {
        return new IndexValuePair();
    }

    /**
     * Create an instance of {@link ObjectClassInfo }
     * 
     */
    public ObjectClassInfo createObjectClassInfo() {
        return new ObjectClassInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WLPECMException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://common.service.wlpecm.wlp.com", name = "WLPECMException")
    public JAXBElement<WLPECMException> createWLPECMException(WLPECMException value) {
        return new JAXBElement<WLPECMException>(_WLPECMException_QNAME, WLPECMException.class, null, value);
    }

}
