//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.wlp.wlpecm.service.responsedto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.wlp.wlpecm.service.ArrayOfArrayOfTns3NillableIndexValuePair;
import com.wlp.wlpecm.service.ArrayOfXsdNillableString;


/**
 * <p>Java class for GetListingRespDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetListingRespDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UUID" type="{http://service.wlpecm.wlp.com}ArrayOf_xsd_nillable_string"/>
 *         &lt;element name="fileType" type="{http://service.wlpecm.wlp.com}ArrayOf_xsd_nillable_string"/>
 *         &lt;element name="listingLineItem" type="{http://service.wlpecm.wlp.com}ArrayOfArrayOf_tns3_nillable_IndexValuePair"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetListingRespDTO", propOrder = {
    "uuid",
    "fileType",
    "listingLineItem"
})
public class GetListingRespDTO {

    @XmlElement(name = "UUID", required = true, nillable = true)
    protected ArrayOfXsdNillableString uuid;
    @XmlElement(required = true, nillable = true)
    protected ArrayOfXsdNillableString fileType;
    @XmlElement(required = true, nillable = true)
    protected ArrayOfArrayOfTns3NillableIndexValuePair listingLineItem;

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfXsdNillableString }
     *     
     */
    public ArrayOfXsdNillableString getUUID() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfXsdNillableString }
     *     
     */
    public void setUUID(ArrayOfXsdNillableString value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the fileType property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfXsdNillableString }
     *     
     */
    public ArrayOfXsdNillableString getFileType() {
        return fileType;
    }

    /**
     * Sets the value of the fileType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfXsdNillableString }
     *     
     */
    public void setFileType(ArrayOfXsdNillableString value) {
        this.fileType = value;
    }

    /**
     * Gets the value of the listingLineItem property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfArrayOfTns3NillableIndexValuePair }
     *     
     */
    public ArrayOfArrayOfTns3NillableIndexValuePair getListingLineItem() {
        return listingLineItem;
    }

    /**
     * Sets the value of the listingLineItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfArrayOfTns3NillableIndexValuePair }
     *     
     */
    public void setListingLineItem(ArrayOfArrayOfTns3NillableIndexValuePair value) {
        this.listingLineItem = value;
    }

}
