//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.wlp.wlpecm.service.responsedto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StoreContentRespDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StoreContentRespDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contentKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contentUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StoreContentRespDTO", propOrder = {
    "contentKey",
    "contentUri"
})
public class StoreContentRespDTO {

    @XmlElement(required = true, nillable = true)
    protected String contentKey;
    @XmlElement(required = true, nillable = true)
    protected String contentUri;

    /**
     * Gets the value of the contentKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentKey() {
        return contentKey;
    }

    /**
     * Sets the value of the contentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentKey(String value) {
        this.contentKey = value;
    }

    /**
     * Gets the value of the contentUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentUri() {
        return contentUri;
    }

    /**
     * Sets the value of the contentUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentUri(String value) {
        this.contentUri = value;
    }

}
