//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.wlp.wlpecm.service.requestdto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wlp.wlpecm.service.requestdto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wlp.wlpecm.service.requestdto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetListingReqDTO }
     * 
     */
    public GetListingReqDTO createGetListingReqDTO() {
        return new GetListingReqDTO();
    }

    /**
     * Create an instance of {@link GetContentReqDTO }
     * 
     */
    public GetContentReqDTO createGetContentReqDTO() {
        return new GetContentReqDTO();
    }

    /**
     * Create an instance of {@link UpdateMetadataReqDTO }
     * 
     */
    public UpdateMetadataReqDTO createUpdateMetadataReqDTO() {
        return new UpdateMetadataReqDTO();
    }

    /**
     * Create an instance of {@link GetRepositoryStatusReqDTO }
     * 
     */
    public GetRepositoryStatusReqDTO createGetRepositoryStatusReqDTO() {
        return new GetRepositoryStatusReqDTO();
    }

    /**
     * Create an instance of {@link StoreContentReqDTO }
     * 
     */
    public StoreContentReqDTO createStoreContentReqDTO() {
        return new StoreContentReqDTO();
    }

    /**
     * Create an instance of {@link GetObjectClassReqDTO }
     * 
     */
    public GetObjectClassReqDTO createGetObjectClassReqDTO() {
        return new GetObjectClassReqDTO();
    }

}
